# Generated by Django 3.2.12 on 2022-05-20 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220520_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_comment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='movie_comment',
            name='user',
        ),
    ]
