# Generated by Django 3.2.12 on 2022-05-22 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_auto_20220520_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_comment',
            name='content',
            field=models.CharField(default='123', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie_comment',
            name='user',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, related_name='movie_comment', to='accounts.user'),
            preserve_default=False,
        ),
    ]
